server.port = 8009
spring.jpa.show-sql = true
spring.datasource.url= jdbc:mysql://localhost:3306/revatureDB1
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
management.security.enabled=false